apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: dedalus-hazelcastclustermanager-template
  app: hazelcast-dedalus
metadata:
  annotations:
    description: |-
      HazelCast Cluster Manager definition it needs Hazelcast Platform Operator installed.
      For more information about using this template, including OpenShift considerations, see http://ci-git.noemalife.loc:8888/paolo.merci/hazelcast-operator/src/master/README.md
    iconClass: icon-d4center
    tags: dedalus-hazelcastoperator,dedalus
  name: dedalus-hazelcastclustermanager
objects:
# :::
# ::: ServiceAccount
# ::: It will create the service account with the aws token to download the images from Dedalus repository
# :::
- apiVersion: v1
  kind: ServiceAccount
  labels:
    app: hazelcast-dedalus
  metadata:
    name: managementcenter-hazelcast
    namespace: ${NAMESPACE}
  imagePullSecrets:
    - name: ${AWS_TOKEN}
  secrets:
    - name: ${AWS_TOKEN}
# :::
# ::: Hazelcast ManagementCenter installation
# ::: It's possible to configure persistent storage and expose the service outside the cluster,
# ::: please reade the notes in the README.md before using persistent storage.
# :::
- apiVersion: hazelcast.com/v1alpha1
  kind: ManagementCenter
  metadata:
    label:
      app: hazelcast-dedalus
    name: managementcenter-hazelcast
    namespace:  ${NAMESPACE}
  spec:
    # externalConnectivity Type describes how Management Center is exposed. possible values: "ClusterIP", "NodePort" and "LoadBalancer" see https://docs.hazelcast.com/operator/latest/api-ref#externalconnectivitytype
    externalConnectivity:
      type: ClusterIP
    hazelcastClusters:
      - address: ${HAZ_SERVER_NAME}
        name: ${HAZ_CLUSTER_NAME}
    imagePullPolicy: IfNotPresent
    persistence:
      enabled: false
    repository: 350801433917.dkr.ecr.eu-west-1.amazonaws.com/enterprise-architect/support
    version: hazelcast-management-center-5.1.1
parameters:
- name: NAMESPACE
  displayName: Namespace where the grafana Operator will be installed in
  description: Type the Namespace where the grafana Operator will be installed in
  required: true
  value:
- name: HAZ_SERVER_NAME
  displayName: Hazelcast StatefulSet Name
  description: Type the name for the StatefulSet created by the operator
  required: true
  value: hazelcast-node
- name: HAZ_CLUSTER_NAME
  displayName: Hazelcast Cluster Name
  description: Type the Name for the Hazelcast Cluster created by the members of the statefulset
  required: true
  value: x1v1fhir_terminology
- name: AWS_TOKEN
  displayName: Secret for AWS token
  description: Secret used to store the AWS token. default value for Openshift 4.x
  required: true
  value: aws-ecr-token
